export const ActionTypes={
    CHANGE_LOCATION:"CHANGE_LOCATION",
    CHANGE_DAILYFORCAST:"CHANGE_DAILYFORCAST",
    CHANGE_WEATHER:"CHANGE_WEATHER",
    CHANGE_SEARCH:"CHANGE_SEARCH",
    REMOVE_SELECTED_WEATHER:"REMOVE_SELECTED_WEATHER",
}